FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /workspace
COPY . .
RUN mvn -DskipTests -q -pl quantor-worker -am clean package

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /workspace/quantor-worker/target/*.jar /app/app.jar
ENV SPRING_PROFILES_ACTIVE=gcp
ENTRYPOINT ["java","-jar","/app/app.jar"]
