FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /workspace
COPY . .
RUN mvn -DskipTests -q -pl quantor-api -am clean package

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /workspace/quantor-api/target/*.jar /app/app.jar
EXPOSE 8080
ENV SPRING_PROFILES_ACTIVE=gcp
ENTRYPOINT ["java","-jar","/app/app.jar"]
